apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-udr-conf
data:
  udrcfg.conf: |
    info:
      version: 1.0.0
      description: UDR initial local configuration

    configuration:
      sbi:
        scheme: http
        ipv4Addr: 0.0.0.0
        port: 29504
      mongodb:
        name: free5gc
        url: mongodb://db:27017
      nrfUri: http://0.0.0.0:29510
