apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nrf
  name: nrf
spec:
  ports:
  - name: "29510"
    port: 29510
    targetPort: 29510
  selector:
    io.kompose.service: nrf
status:
  loadBalancer: {}
