apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-ausf-conf
data:
  ausfcfg.conf: |
    info:
      version: 1.0.0
      description: AUSF initial local configuration

    configuration:
      sbi:
        scheme: http
        ipv4Addr: 0.0.0.0
        port: 29509
      serviceNameList:
        - nausf-auth
      nrfUri: http://0.0.0.0:29510
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
