apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: udm
  name: udm
spec:
  ports:
  - name: "29503"
    port: 29503
    targetPort: 29503
  selector:
    io.kompose.service: udm
status:
  loadBalancer: {}
