apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-conf
  namespace: 5gtest
data:
  webuicfg.conf: |
    info:
      version: 1.0.0
      description: Docker-WebUI initial local configuration

    configuration:
      mongodb:
        name: free5gc
        url: mongodb://db:27017
