apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-nrf
  name: free5gc-nrf
  namespace: 5gtest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-nrf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-nrf
    spec:
      containers:
      - args:
        - ./nrf
        - -nrfcfg
        - ../config/nrfcfg.conf
        env:
        - name: DB_URI
          value: mongodb://db/free5gc
        - name: GIN_MODE
          value: release
        image: 95.217.176.245:8082/dtdocker/free5gc-nrf:1.0
        imagePullPolicy: "IfNotPresent"
        name: nrf
        ports:
        - containerPort: 29510
        resources: {}
        volumeMounts:
        - mountPath: /free5gc/config/nrfcfg.conf
          name: cfgmap0
          subPath: nrfcfg.conf
        - mountPath: /free5gc/config/free5GC.conf
          name: cfgmap1
          subPath: free5GC.conf
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: free5gc-nrf-claim0
        persistentVolumeClaim:
          claimName: free5gc-nrf-claim0
      - name: free5gc-nrf-claim1
        persistentVolumeClaim:
          claimName: free5gc-nrf-claim1
      - name: cfgmap0
        configMap:
          name: free5gc-nrf-conf
      - name: cfgmap1
        configMap:
          name: free5gc-conf
status: {}
