apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-upf-2
  name: free5gc-upf-2
  namespace: 5gtest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-upf-2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-upf-2
    spec:
      containers:
      - args:
        image: nginx
        imagePullPolicy: "IfNotPresent"
        name: upf2
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /free5gc/config/upfcfg.yaml
          name: cfgmap0
          subPath: upfcfg2.yaml
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: free5gc-upf-2-claim0
        persistentVolumeClaim:
          claimName: free5gc-upf-2-claim0
      - name: cfgmap0
        configMap:
          name: free5gc-upf2-conf
status: {}
